### ISSUE TITLE
[Feature request] Lerna structure support - define directories for labelling

### ISSUE THREAD

**Issue by clifford-lc** [adamzolyak/monorepo-pr-labeler-action#1]
Quick suggestion, given some of the approaches for monorepo libraries, is to nest package folders inside of subdirectories instead of in the root.

If there was an array we could parse into the action configuration to tell the API where to look for changes would be very useful.

eg. Given `Lerna` structure

```
- packages
-- module1
-- module2
- package.json
```
My PR currently is labelled `packages`

### Request

Given structure:

```
- packages
-- module1
-- module2
- package.json
```

Configure GH action

```
action "Label PR Monorepos" {
  uses = "adamzolyak/monorepo-pr-labeler-action@1.0.1"
  secrets = ["GITHUB_TOKEN"]
  dir = ["/packages", "/src"] // Leave empty for default directory "root"
}
```

Outcome: PR's label per subdirectory instead

**Comment by adamzolyak** [comment]
👋 thanks for the suggestion.  Looking into it.

**Comment by adamzolyak** [comment]
@clifford-lc per your suggestion

> `dir = ["/packages", "/src"] // Leave empty for default directory "root"`

Are you thinking it would be helpful to configure multiple directories that contain modules?  Just wanted to double check and not assume.

**Comment by clifford-lc** [comment]
> Are you thinking it would be helpful to configure multiple directories that contain modules? Just wanted to double check and not assume.

Correct, I think it would be useful to define the directory/directories that contain the module folders to loop through.

> https://github.com/lerna/lerna#what-does-a-lerna-repo-look-like
In my use case, the `lerna.json` file defines 2 directory locations to semantically split module folders, in JSON it looks a little like this:

```
"packages": [
    "packages/*",
    "services/*"
]
```

I would expect that if I were to define the following config for the GH action, it would find the folders within these directories instead of sniffing the root directory:

```
dir = ["/packages", "/services"]
```

I'm not sure if the label would have to change, perhaps eg. `Repo: Foo` and `Repo: Bar` from respective `/packages/foo` and `/services/bar` is still fine. Otherwise `Repo: packages/foo` as a label could make sense, but if someone were to define deeper subdirectories, maybe some other issues may arise `Repo: really/deep/subdirectory/for/the/insane/package`

**Comment by adamzolyak** [comment]
@clifford-lc check out the PR w/ a proposed implementation - feedback appreciated 👏

**Comment by clifford-lc** [comment]
@adamzolyak It looks good to me, it hits the `lerna` monorepo style 👍 

I wonder if BASE_ENV definitions does/should support paths like `path/to/package|module-folder`? Something for later perhaps.

**Comment by adamzolyak** [comment]
Released https://github.com/marketplace/actions/monorepo-pr-repo-labeler?version=1.1.1.  Thanks for the help @clifford-lc 👏👏👏!
