### ISSUE TITLE
Upgrade to node v14 

### ISSUE THREAD

**Issue by anshulsahni** [adamzolyak/monorepo-pr-labeler-action#15]
Hi @adamzolyak, any specific reason for us to stick node version 8 for this github action, I mean, we already node 14 out and testd in my local all the tests seems to be working fine, do you think there will be any problem if we upgrade to `node:14` which is an LTS since long now

**Comment by adamzolyak** [comment]
@anshulsahni I don't see any issues with Node 14.  Feel free to bump it in your PR.  If not, I'll bump it.  I need to update a few package versions anyway after #16 is merged and before releasing an updated version of the GH Action.
