### ISSUE TITLE
Using gh action as a CI

### ISSUE THREAD

**Issue by anshulsahni** [adamzolyak/monorepo-pr-labeler-action#18]
Since this itself a github action shouldn't this be using a gh action itself for as CI tool instead of circleCI﻿

**Comment by adamzolyak** [comment]
@anshulsahni sure.  Feel free to PR it.

**Comment by adamzolyak** [comment]
@anshulsahni also if you're interested in being a maintainer for this repo along with me, I can add you as a contributor.

**Comment by anshulsahni** [comment]
Sure @adamzolyak, I would love to

**Comment by adamzolyak** [comment]
@anshulsahni awesome 🙌 !  After a bit more investigation, it seems that I need to migrate this repo to an organization account so that I can add additional maintainers and have more granular permissions.  I created #19 to track this work.
